### ISSUE TITLE
i cant search for '+++'

### ISSUE THREAD

**Issue by two-dogs** [rogershen/chrome-regex-search#16]
System:    Host: linux-fcke Kernel: 4.12.8-1-default x86_64 bits: 64 gcc: 7.1.1
           Desktop: KDE Plasma 5.10.4 (Qt 5.9.1) dm: sddm,sddm Distro: openSUSE Tumbleweed 20170822

Information for package google-chrome-beta:
-------------------------------------------
Repository     : google                               
Name           : google-chrome-beta                   
Version        : 61.0.3163.59-1                       
Arch           : x86_64                               
Vendor         : Google Inc.                          
Installed Size : 343.7 MiB                            
Installed      : Yes                                  
Status         : up-to-date                           
Source package : google-chrome-beta-61.0.3163.59-1.src
Summary        : Google Chrome (beta)                 
Description    :                                      
    The web browser from Google

    Google Chrome is a browser that combines a minimal design with sophisticated technology to make the web faster, safer, and easier.

using extension https://chrome.google.com/webstore/detail/chrome-regex-search/bpelaihoicobbkgmhcbikncnpacdbknn/support?utm_source=chrome-app-launcher-info-dialog

tested on this site https://cgit.kde.org/konversation.git/commit/?id=72de2027f3d3e7a0c48aef6acd666e04fc0b19b1

**Comment by PixelMaster98** [comment]
Did you search for "+++" or "\+\+\+"? You'd need the latter one, since "+" is a quantifier (i.e. a special char that has to be escaped with "\") in regex.
