### ISSUE TITLE
Is it possible to have a function to copy those selected text?

### ISSUE THREAD

**Issue by TerrySunTW** [rogershen/chrome-regex-search#18]
This is a really useful extension. User will need a function to copy those selected text. Is there any way to do this?

**Comment by TerrySunTW** [comment]
Or maybe just need to show all selection text in somewhere.
you could use this javascript to do that.

Array.prototype.forEach.call( document.querySelectorAll("highlight-tag"), function( el, i ) {  console.log( el.textContent );});

**Comment by mtiigi** [comment]
I wanted this too :+1:. See #32.

**Comment by rogershen** [comment]
I will merge the pull request.
