### ISSUE TITLE
Operate on file:// URLs also

### ISSUE THREAD

**Issue by cxw42** [rogershen/chrome-regex-search#2]
Nice extension!  Would you please update the manifest (and source?) so it will also work on file:// URLs?  My use case involves a lot of locally-stored HTML.  

I have not done any Chrome extension development myself, but found [this doc page](https://developer.chrome.com/extensions/match_patterns) and [this SO question](http://stackoverflow.com/q/9850326)* that suggest adding `"file://*/*"` to the `matches` in `manifest.json` should do it.

Thank you!

*attrib: [Anthony](http://stackoverflow.com/users/49478/anthony)

**Comment by rogershen** [comment]
Hello Anthony, thanks for noticing this. I will add the "file://*/*" extension and update the app.

**Comment by cxw42** [comment]
Roger, works for me!  Thanks very much!
