### ISSUE TITLE
[Feature Request] Improve use cases of regex search engine

### ISSUE THREAD

**Issue by busyworker** [rogershen/chrome-regex-search#28]
Often, when we search something in Chrome, we mean to select it for copy paste or to click the link. In Chrome, when we search for something and then hit escape, we have the found entry we were on selected and we can just hit Ctrl + C. Unfortunately, this is not the case here. 

- The text is just highlighted and not selected. As such, I would like to propose that we modify the searcher to make it select the entry we're on instead of highlighting it in a different color and to remove the highlighting when we exit the searcher via Esc.

- Also, in Chrome, when we hit Ctrl + Enter while we've selected part of a text via Ctrl + F, it has the same effect as clicking that selection. This would also be a very useful feature to have.

**Comment by rogershen** [comment]
There are two pull requests which will add these features. I will add merge them into the master branch.
