### ISSUE TITLE
Highlight search text when re-opening search box via hotkey

### ISSUE THREAD

**Issue by cxw42** [rogershen/chrome-regex-search#3]
Roger, would it be possible for the search form to open with previously-entered text selected in the input field?  That way, if I had a new regex to enter, I could type it without first having to clear the field.  

Example: I have v1.0.2 installed and mapped to Ctrl+Shift+F.  When I hit the hotkey and enter a regex, everything works fine.  I then hit Esc to close the search box, and hit Ctrl+Shift+F again.  The text I entered is still there (which is fine), but the text is not selected.  In order to start a new search, I have to clear the box first.

There is an easy workaround, of course - Shift+Home, Del to clear the box :) .  However, I also use Chrome's built-in find (Ctrl+F) for plain-text searching.  The behaviour I am requesting is the same as that of the Chrome find.  The consistency between the two would make it much easier for me to use Regex Search without regular "Oops --- forgot to clear the box!" moments.

Thanks for considering this request!

Chris White

**Comment by WofWca** [comment]
Are you sure this is resolved? Does not work for me.
