### ISSUE TITLE
initial ^ not working

### ISSUE THREAD

**Issue by dcambria** [rogershen/chrome-regex-search#34]
initial ^ not working in txt files, like http://data.iana.org/TLD/tlds-alpha-by-domain.txt

**Comment by rogershen** [comment]
Right now the extension only handles HTML pages. The way the code handles highlighting uses CSS styling.  This is a limitation of what is possible in a Chrome extension. Unfortunately, I don't have a hook to the native highlighting used by Google Chrome so it can't really support other formats.
