### ISSUE TITLE
New User - 2 Requests

### ISSUE THREAD

**Issue by johnrs** [rogershen/chrome-regex-search#7]
Hi.  I love it!  I've set it to Ctrl-F.  :)

I do both case sensitive and insensitive searches.  Having to pull up the Options page to switch between the two modes is a bit of a nuisance.  I wonder if this option could be moved to the search box instead?

The only thing I miss, compared to Chrome's search, is marking the finds on the scroll bar.  Any chance of this?  Even if it meant adding a bar next to the scroll bar, I think it would be handy.

Thanks!

**Comment by rogershen** [comment]
Hi,
Thanks for the suggestions. I have added case insensitive search to the popup menu. This will be in version 1.0.7. I'm not sure about Chrome extension support for your second request, but I will certainly look into it.

**Comment by johnrs** [comment]
Thanks very much!
